version: "3"
services:
  postgres:
    stdin_open: true
    tty: true
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    expose:
      - 5432
  replica:
    stdin_open: true
    tty: true
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=replica
    ports:
      - 5433:5432
  subscriber:
    stdin_open: true
    tty: true
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=subscriber
    ports:
      - 5433:5432
